manipulator:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.05
  #link_prefix: prbt_
  #prefix: prbt_
  kinematics_solver: prbt_manipulator/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  link_prefix: prbt_
